nombre: Informe de error
Descripción: Presentar un informe de error.
Título: "[Error]: "
etiquetas: ["error", "triaje"]
proyectos: ["octo-org/1", "octo-org/44"]
cesionarios:
  - octogato
tipo: error
cuerpo:
  - tipo: markdown
    atributos:
      valor: |
        ¡Gracias por tomarse el tiempo para completar este informe de errores!
  - tipo: entrada
    id: contacto
    atributos:
      etiqueta: Datos de contacto
      Descripción:¿Cómo podemos ponernos en contacto con usted si necesitamos más información?
      marcador de posición: p. ej. email@example.com
    validaciones:
      requerido: falso
  - tipo: área de texto
    id: qué pasó
    atributos:
      etiqueta:¿Que pasó?
      Descripción:Cuéntanos también ¿Qué esperabas que pasara?
      marcador de posición: ¡Cuéntanos qué ves!
      valor: "¡Ocurrió un error!"
    validaciones:
      requerido: verdadero
  - tipo: desplegable
    id: versión
    atributos:
      etiqueta: Versión
      Descripción:¿Qué versión de nuestro software está utilizando?
      opciones:
        - 1.0.2 (predeterminado)
        - 1.0.3 (Edge)
      predeterminado: 0
    validaciones:
      requerido: verdadero
  - tipo: desplegable
    id: navegadores
    atributos:
      Etiqueta: ¿En qué navegadores ves el problema?
      múltiple: verdadero
      opciones:
        - Firefox
        - Cromo
        - Safari
        - Microsoft Edge
  - tipo: área de texto
    id: registros
    atributos:
      etiqueta: Salida de registro relevante
      Descripción: Copie y pegue cualquier salida de registro relevante. Se formateará automáticamente en el código, así que no necesita comillas invertidas.
      renderizar: shell
  - tipo: casillas de verificación
    id: términos
    atributos:
      etiqueta: Código de conducta
      Descripción: Al enviar este problema, usted acepta seguir nuestro [Código de conducta](https://example.com).
      opciones:
        - etiqueta: Acepto seguir el Código de conducta de este proyecto
          requerido: verdadero
